myprogress_nodes = {}

myprogress_nodes.digging = {
    ["default:dirt"] = 1,
    ["default:dirt_with_grass"] = 1,
    ["default:dirt_with_dry_grass"] = 1,
    ["default:dirt_with_snow"] = 1,
    ["default:sand"] = 1,
    ["default:desert_sand"] = 1,
    ["default:gravel"] = 1,
    ["default:clay"] = 1,
    ["default:silver_sand"] = 1,
    ["ethereal:crystal_dirt"] = 1,
    ["ethereal:fiery_dirt"] = 1,
    ["ethereal:gray_dirt"] = 1,
    ["ethereal:cold_dirt"] = 1,
    ["ethereal:mushroom_dirt"] = 1,
    ["ethereal:jungle_dirt"] = 1,
}

myprogress_nodes.mining = {
    ["default:stone"] = 1,
    ["default:desert_stone"] = 1,
    ["default:cobble"] = 1,
    ["default:stone_with_coal"] = 2,
    ["default:stone_with_iron"] = 3,
    ["default:stone_with_gold"] = 5,
    ["default:stone_with_mese"] = 8,
    ["default:stone_with_diamond"] = 15,
    ["myores:tin_ore"] = 2,
    ["myores:silver_ore"] = 3,
    ["myores:platinum_ore"] = 6,
    ["myores:aluminum_ore"] = 2,
    ["myores:copper_ore"] = 2,
    ["myores:lead_ore"] = 2,
    ["myores:zinc_ore"] = 2,
    ["myores:ruby_ore"] = 10,
    ["myores:sapphire_ore"] = 10,
    ["myores:emerald_ore"] = 10,
    ["ethereal:crystal_ore"] = 8,
}

myprogress_nodes.lumbering = {
    ["default:tree"] = 1,
    ["default:jungletree"] = 1,
    ["default:pine_tree"] = 1,
    ["default:acacia_tree"] = 1,
    ["default:aspen_tree"] = 1,
    ["moretrees:apple_tree_trunk"] = 1,
    ["moretrees:birch_trunk"] = 1,
    ["moretrees:beech_trunk"] = 1,
    ["moretrees:cedar_trunk"] = 1,
    ["moretrees:cherry_trunk"] = 1,
    ["moretrees:fir_trunk"] = 1,
    ["moretrees:oak_trunk"] = 1,
    ["moretrees:palm_trunk"] = 1,
    ["moretrees:rubber_tree_trunk"] = 1,
    ["moretrees:sequoia_trunk"] = 1,
    ["moretrees:spruce_trunk"] = 1,
    ["moretrees:willow_trunk"] = 1,
    ["ethereal:willow_trunk"] = 1,
    ["ethereal:redwood_trunk"] = 1,
    ["ethereal:frost_trunk"] = 1,
    ["ethereal:yellow_trunk"] = 1,
    ["ethereal:palm_trunk"] = 1,
    ["ethereal:banana_trunk"] = 1,
    ["ethereal:birch_trunk"] = 1,
    ["ethereal:bamboo"] = 1,
}

myprogress_nodes.farming = {
    ["farming:wheat_8"] = 1,
    ["farming:cotton_8"] = 1,
    ["farming:corn_8"] = 1,
    ["farming:coffee_5"] = 1,
    ["farming:raspberry_4"] = 1,
    ["farming:blueberry_4"] = 1,
    ["farming:beanbush_4"] = 1,
    ["farming:grapebush_3"] = 1,
    ["farming:barley_7"] = 1,
    ["farming:rhubarb_3"] = 1,
    ["farming:potato_4"] = 1,
    ["farming:tomato_7"] = 1,
    ["farming:carrot_8"] = 1,
    ["farming:garlic_5"] = 1,
    ["farming:onion_5"] = 1,
    ["farming:pepper_5"] = 1,
    ["farming:pumpkin_8"] = 1,
    ["farming:cucumber_4"] = 1,
    ["farming:cabbage_6"] = 1,
    ["farming:lettuce_5"] = 1,
    ["farming:blackberry_4"] = 1,
    ["farming:vanilla_8"] = 1,
    ["farming:soybean_5"] = 1,
    ["farming:rice_8"] = 1,
    ["farming:mint_4"] = 1,
    ["farming:artichoke_5"] = 1,
    ["farming:parsley_3"] = 1,
    ["farming:spinach_4"] = 1,
    ["default:apple"] = 1,
    ["default:papyrus"] = 1,
    ["default:cactus"] = 1,
    ["farming:cocoa_beans"] = 1,
    ["farming:pineapple_8"] = 1,
    ["ethereal:strawberry_7"] = 1,
    ["ethereal:onion_5"] = 1,
    ["ethereal:banana"] = 1,
    ["ethereal:orange"] = 1,
    ["ethereal:coconut"] = 1,
    ["ethereal:golden_apple"] = 5,
    ["ethereal:wild_onion_4"] = 1,
    ["ethereal:fern"] = 1,
    ["ethereal:snow_onion"] = 1,
}

myprogress_nodes.machines = {
    ["myprogress:master_smelter"]   = { skill = "mining",  level = 20 },
    ["myprogress:master_sawmill"]   = { skill = "lumbering", level = 20 },
    ["myprogress:master_harvester"] = { skill = "farming", level = 20 },
    ["myprogress:master_sifter"]    = { skill = "digging", level = 20 },
}
